// This model was generated by Forest CLI. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const Acts = sequelize.define('acts', {
    date: {
      type: DataTypes.DATE,
    },
    comment: {
      type: DataTypes.STRING,
    },
  }, {
    tableName: 'acts',
    timestamps: false,
    schema: process.env.DATABASE_SCHEMA,
  });
  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v6/reference-guide/relationships#adding-relationships.
  Acts.associate = (models) => {
    Acts.belongsTo(models.patients, {
      foreignKey: {
        name: 'patientIdKey',
        field: 'patientId',
      },
      as: 'patient',
    });
    Acts.belongsTo(models.practitioners, {
      foreignKey: {
        name: 'practitionerIdKey',
        field: 'practitionerId',
      },
      as: 'practitioner',
    });
  };

  return Acts;
};
