// This model was generated by Forest CLI. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const Patients = sequelize.define('patients', {
    firstName: {
      type: DataTypes.STRING,
    },
    lastName: {
      type: DataTypes.STRING,
    },
    birthDate: {
      type: DataTypes.DATE,
    },
    socialNumber: {
      type: DataTypes.STRING,
    },
    sexe: {
      type: DataTypes.ENUM(
        'M',
        'F',
      ),
      defaultValue: "M",
      allowNull: false,
    },
  }, {
    tableName: 'patients',
    timestamps: false,
    schema: process.env.DATABASE_SCHEMA,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v6/reference-guide/relationships#adding-relationships.
  Patients.associate = (models) => {
    Patients.belongsTo(models.practitioners, {
      foreignKey: {
        name: 'assignedPractitionersKey',
        field: 'assignedPractitioners',
      },
      as: 'assignedPractitioners',
    });
    Patients.hasMany(models.acts, {
      foreignKey: {
        name: 'patientIdKey',
        field: 'patientId',
      },
      as: 'acts',
    });
  };

  return Patients;
};
