// This model was generated by Forest CLI. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const Practitioners = sequelize.define('practitioners', {
    firstName: {
      type: DataTypes.STRING,
    },
    lastName: {
      type: DataTypes.STRING,
    },
    birthDate: {
      type: DataTypes.DATE,
    },
    practitionerId: {
      type: DataTypes.STRING,
    },
  }, {
    tableName: 'practitioners',
    timestamps: false,
    schema: process.env.DATABASE_SCHEMA,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v6/reference-guide/relationships#adding-relationships.
  Practitioners.associate = (models) => {
    Practitioners.hasMany(models.acts, {
      foreignKey: {
        name: 'practitionerIdKey',
        field: 'practitionerId',
      },
      as: 'acts',
    });
    Practitioners.hasMany(models.patients, {
      foreignKey: {
        name: 'assignedPractitionersKey',
        field: 'assignedPractitioners',
      },
      as: 'assignedPractitionersPatients',
    });
  };

  return Practitioners;
};
